### ISSUE TITLE
Merge apk error use the latest commit ` d8ef9db`

### ISSUE THREAD

**Issue by xiaoyvyv** [REAndroid/ARSCLib#32]
Merge apk error use the latest commit ` d8ef9db`

```

W  java.lang.IllegalArgumentException: java.io.EOFException: Finished reading: 0
W  	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:523)
W  	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:530)
W  	at com.reandroid.apk.ApkModule.getVolatileTableStringPool(ApkModule.java:597)
W  	at com.reandroid.apk.ApkBundle.mergeStringPools(ApkBundle.java:81)
W  	at com.reandroid.apk.ApkBundle.mergeModules(ApkBundle.java:44)
W  	at com.xiaoyv.manager.tool.apk.editor.merge.ApkMerger.run(ApkMerger.kt:62)
W  	at com.xiaoyv.manager.tool.apk.editor.merge.ApkMerger$Companion.merge(ApkMerger.kt:245)
W  	at com.xiaoyv.manager.tool.apk.editor.merge.ApkMerger$Companion.merge(ApkMerger.kt:214)
W  	at com.xiaoyv.manager.ui.file.FileSelectorViewModel$mergeApksFile$2$1.invokeSuspend(FileSelectorViewModel.kt:300)
W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W  	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
W  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
W  Caused by: java.io.EOFException: Finished reading: 0
W  	at com.reandroid.arsc.io.BlockReader.readFully(BlockReader.java:204)
W  	at com.reandroid.arsc.io.BlockReader.readFully(BlockReader.java:187)
W  	at com.reandroid.arsc.item.BlockItem.onReadBytes(BlockItem.java:100)
W  	at com.reandroid.arsc.base.Block.readBytes(Block.java:48)
W  	at com.reandroid.arsc.base.BlockContainer.onReadBytes(BlockContainer.java:149)
W  	at com.reandroid.arsc.header.HeaderBlock.onReadBytes(HeaderBlock.java:151)
W  	at com.reandroid.arsc.base.Block.readBytes(Block.java:48)
W  	at com.reandroid.arsc.base.BlockContainer.onReadBytes(BlockContainer.java:149)
W  	at com.reandroid.arsc.chunk.Chunk.onReadBytes(Chunk.java:59)
W  	at com.reandroid.arsc.base.Block.readBytes(Block.java:48)
W  	at com.reandroid.arsc.chunk.TableBlock.onReadBytes(TableBlock.java:147)
W  	at com.reandroid.arsc.base.Block.readBytes(Block.java:48)
W  	at com.reandroid.arsc.chunk.TableBlock.readBytes(TableBlock.java:161)
W  	at com.reandroid.arsc.chunk.TableBlock.load(TableBlock.java:326)
W  	at com.reandroid.apk.ApkModule.loadTableBlock(ApkModule.java:615)
W  	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:517)
W  	... 16 more

**Comment by xiaoyvyv** [comment]
Here is the test apk.zip [https://fileport.io/KvP7WMwNf95P](https://fileport.io/KvP7WMwNf95P)

**Comment by xiaoyvyv** [comment]
After I restored the code submitted in this place, Merge apks worked normally 
![图片](https://user-images.githubusercontent.com/29088158/234344919-6037d010-0690-4d7c-aa6b-a585e9896559.png)

**Comment by REAndroid** [comment]
Check the latest [commit](https://github.com/REAndroid/ARSCLib/commit/ce27a1bf4f0fd7cc143b679b7e623947a4f48c18)
