### ISSUE TITLE
Crash due to unsupported regular expression in Android

### ISSUE THREAD

**Issue by MuntashirAkon** [REAndroid/ARSCLib#35]
```
Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 8:
^\s*(?<A>https?://[^:\s]+)(:(?<B>([^:/\s]+)))?\s*$
        ^
  at java.util.regex.Pattern.compileImpl(Native Method)
  at java.util.regex.Pattern.compile(Pattern.java:411)
  at java.util.regex.Pattern.<init>(Pattern.java:394)
  at java.util.regex.Pattern.compile(Pattern.java:381)
  at com.reandroid.xml.SchemaAttr.<clinit>(SchemaAttr.java:123)
  ... 17 more
```

PS: This appears to be a Android/ICU4C limitation

**Comment by MuntashirAkon** [comment]
This is causing the issue:

```regex
"^\\s*(?<A>https?://[^:\\s]+)(:(?<B>([^:/\\s]+)))?\\s*$"
```

Instead of a named capturing group, use the typical numbered groups, e.g.

```regex
^\s*(https?:\/\/[^:\s]+)(:([^:\/\s]+))?\s*$
```

The equivalent of `A` and `B` would be group 1 and 3.

**Comment by MuntashirAkon** [comment]
This issue was fixed, too. Thanks!
