### ISSUE TITLE
error 1.2.0 and master

### ISSUE THREAD

**Issue by TimScriptov** [REAndroid/ARSCLib#48]
java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "value" is null
	at com.android.org.kxml2.io.KXmlSerializer.attribute(KXmlSerializer.java:432)
	at com.reandroid.apk.xmldecoder.EntryWriterSerializer.attribute(EntryWriterSerializer.java:52)
	at com.reandroid.apk.xmldecoder.EntryWriterSerializer.attribute(EntryWriterSerializer.java:23)
	at com.reandroid.apk.xmldecoder.BagDecoderCommon.decode(BagDecoderCommon.java:52)
	at com.reandroid.apk.xmldecoder.BagDecoderCommon.decode(BagDecoderCommon.java:24)
	at com.reandroid.apk.xmldecoder.DecoderResTableEntryMap.decode(DecoderResTableEntryMap.java:39)
	at com.reandroid.apk.xmldecoder.XMLEntryDecoder.decode(XMLEntryDecoder.java:61)
	at com.reandroid.apk.xmldecoder.XMLEntryDecoder.decode(XMLEntryDecoder.java:87)
	at com.reandroid.apk.xmldecoder.XMLEntryDecoderSerializer.decode(XMLEntryDecoderSerializer.java:56)
	at com.reandroid.apk.xmldecoder.XMLEntryDecoderSerializer.decodeUniqueConfigs(XMLEntryDecoderSerializer.java:50)
	at com.reandroid.apk.xmldecoder.XMLEntryDecoderSerializer.decode(XMLEntryDecoderSerializer.java:42)
	at com.reandroid.apk.ApkModuleXmlDecoder.decodeValues(ApkModuleXmlDecoder.java:298)
	at com.reandroid.apk.ApkModuleXmlDecoder.decodeValues(ApkModuleXmlDecoder.java:294)
	at com.reandroid.apk.ApkModuleXmlDecoder.decodeValues(ApkModuleXmlDecoder.java:282)
	at com.reandroid.apk.ApkModuleXmlDecoder.decodeResourceTable(ApkModuleXmlDecoder.java:63)
	at com.reandroid.apk.ApkModuleDecoder.decode(ApkModuleDecoder.java:48)

**Comment by REAndroid** [comment]
This issue might be similar to #47 , If not please share your apk

**Comment by REAndroid** [comment]
Check the latest
