### ISSUE TITLE
NPE in xml decoder

### ISSUE THREAD

**Issue by kiber-io** [REAndroid/ARSCLib#58]
When trying to decompile in xml mode (in json mode, everything is ok), the attached apk crashes with an error (stack trace from apkeditor)
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "value" is null                                                                                                                                                                            
        at com.android.org.kxml2.io.KXmlSerializer.attribute(KXmlSerializer.java:432)
        at com.reandroid.arsc.coder.xml.XmlCoder$BagChild.decodeStyle(XmlCoder.java:439)
        at com.reandroid.arsc.coder.xml.XmlCoder$BagChild.decode(XmlCoder.java:384)
        at com.reandroid.arsc.coder.xml.XmlCoder$ValuesXml.decodeBag(XmlCoder.java:157)
        at com.reandroid.arsc.coder.xml.XmlCoder$ValuesXml.decode(XmlCoder.java:146)
        at com.reandroid.arsc.coder.xml.XmlCoder$ValuesXml.decode(XmlCoder.java:127)
        at com.reandroid.arsc.coder.xml.XmlCoder$ValuesXml.decode(XmlCoder.java:118)
        at com.reandroid.arsc.coder.xml.XmlCoder$ValuesXml.decodePackage(XmlCoder.java:108)
        at com.reandroid.arsc.coder.xml.XmlCoder$ValuesXml.decodeTable(XmlCoder.java:90)
        at com.reandroid.arsc.coder.xml.XmlCoder$ValuesXml.decodeTable(XmlCoder.java:83)
        at com.reandroid.apk.ApkModuleXmlDecoder.decodeValues(ApkModuleXmlDecoder.java:273)
        at com.reandroid.apk.ApkModuleXmlDecoder.decodeResourceTable(ApkModuleXmlDecoder.java:60)
        at com.reandroid.apk.ApkModuleDecoder.decode(ApkModuleDecoder.java:48)
        at com.reandroid.apkeditor.decompile.Decompiler.run(Decompiler.java:62)
        at com.reandroid.apkeditor.decompile.Decompiler.execute(Decompiler.java:127)
        at com.reandroid.apkeditor.Main.execute(Main.java:81)
        at com.reandroid.apkeditor.Main.execute(Main.java:64)
        at com.reandroid.apkeditor.Main.main(Main.java:36)
```

APK: https://mega.nz/file/Ax82ESYQ#yhKTPKpplRqhqQcmGPKmlKO2lPR4AY3R3L1fOlOIfqE

**Comment by REAndroid** [comment]
Same issue as #47 before switching new xml decoder, i forgot to consider this scenario. Fixed with : https://github.com/REAndroid/ARSCLib/commit/a52d8fdf641da2955bee9139fe059657de4d1107
