### ISSUE TITLE
`ResXmlDocument#decodeToXml()` is not processing namespaces correctly

### ISSUE THREAD

**Issue by MuntashirAkon** [REAndroid/ARSCLib#60]
```java
ResXmlDocument xmlBlock = new ResXmlDocument();
try (BlockReader reader = new BlockReader(byteBuffer.array())) {
    xmlBlock.readBytes(reader);
    xmlBlock.setPackageBlock(getFrameworkPackageBlock());
    return xmlBlock.decodeToXml();
}
```

For Google Play Services, it's throwing an `IllegalArgumentException`.

```
java.lang.IllegalArgumentException: Namespace not found for prefix: ns2
	at com.reandroid.xml.XMLElement.setName(XMLElement.java:397)
	at com.reandroid.xml.XMLElement.setName(XMLElement.java:377)
	at com.reandroid.xml.XMLElement.<init>(XMLElement.java:42)
	at com.reandroid.arsc.chunk.xml.ResXmlElement.decodeToXml(ResXmlElement.java:1430)
	at com.reandroid.arsc.chunk.xml.ResXmlElement.decodeToXml(ResXmlElement.java:1452)
	at com.reandroid.arsc.chunk.xml.ResXmlDocument.decodeToXml(ResXmlDocument.java:488)
	at io.github.muntashirakon.AppManager.apk.parser.AndroidBinXmlDecoder.decodeToXml(AndroidBinXmlDecoder.java:5)
```

**Comment by MuntashirAkon** [comment]
Related issue: https://github.com/MuntashirAkon/AppManager/issues/1164

`ResXmlPullParser` is working correctly as expected.

**Comment by REAndroid** [comment]
Try `ResXmlDocument#autoSetAttributeNamespaces` just before decoding, this will automatically fixes any errors on namespaces. 
Maybe you need to do the same for attribute names `autoSetAttributeNames`

**Comment by MuntashirAkon** [comment]
> Try `ResXmlDocument#autoSetAttributeNamespaces` just before decoding, this will automatically fixes any errors on namespaces. Maybe you need to do the same for attribute names `autoSetAttributeNames`

Didn't work. The issue persists.

**Comment by REAndroid** [comment]
You are right, i didn't test but fixed with :  https://github.com/REAndroid/ARSCLib/commit/d20b0a8ee2dffb63912cfd923eac932f7a7e323c

**Comment by MuntashirAkon** [comment]
Thanks.
