### ISSUE TITLE
 ApkModule.loadApkFile(file) crash

### ISSUE THREAD

**Issue by mahdizareeii** [REAndroid/ARSCLib#72]
Hi, when I want to load a file in API 21 (android 5) I'm getting following error but in API 34 its ok, thanks in advance to helping me.

java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
                                                                                                    	at com.reandroid.archive.io.ZipFileInput.getFileChannel(ZipFileInput.java:84)
                                                                                                    	at com.reandroid.archive.io.ZipFileInput.getFooter(ZipFileInput.java:69)
                                                                                                    	at com.reandroid.archive.block.EndRecord.findEndRecord(EndRecord.java:61)
                                                                                                    	at com.reandroid.archive.model.CentralFileDirectory.visit(CentralFileDirectory.java:48)
                                                                                                    	at com.reandroid.archive.Archive.<init>(Archive.java:46)
                                                                                                    	at com.reandroid.archive.ArchiveFile.<init>(ArchiveFile.java:30)
                                                                                                    	at com.reandroid.archive.ArchiveFile.<init>(ArchiveFile.java:33)
                                                                                                    	at com.reandroid.apk.ApkModule.loadApkFile(ApkModule.java:1308)
                                                                                                    	at com.reandroid.apk.ApkModule.loadApkFile(ApkModule.java:1305)
                                                                                                    	at com.appstudio.test.appmaker.AppMaker.assembleFile(AppMaker.kt:42)

**Comment by mahdizareeii** [comment]
i added your module in my project, so I don't have access to modify your file, unless I copy all your file into my project :)

**Comment by cgapk123** [comment]
> As documented here [File#toPath()](https://developer.android.com/reference/java/io/File#toPath()) is introduced on API 26.
> 
> If you can, at [ZipFileInput](https://github.com/REAndroid/ARSCLib/blob/9bc3276391d129eb086f045fbd91479e96aeb23a/src/main/java/com/reandroid/archive/io/ZipFileInput.java#L84): change `fileChannel = FileChannel.open(this.file.toPath(), StandardOpenOption.READ);` to `fileChannel = new FileInputStream(file).getChannel();`

Request the latest Releases

**Comment by mahdizareeii** [comment]
i know it, but the REAndroid should fix it, Im using the latest version

**Comment by kaanelloed** [comment]
@mahdizareeii I tested it myself, getting ARSCLib to work in api 21 would require a lot of changes. For now, I'm enabling [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) ([nio](https://android-developers.googleblog.com/2023/02/api-desugaring-supporting-android-13-and-java-nio.html) version) in my project to make it work.

I'm considering making an api 21-compatible fork.

**Comment by mahdizareeii** [comment]
@kaanelloed i'll try it, thanks my bro
